blog/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from . import views

app_name = "blog"

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('posts/publish/<pk>', views.publish_post, name='post_publish'),
    path('myposts/', views.MyPostsListView.as_view(), name='mypost_list'),
    path('posts/new', views.PostCreateView.as_view(), name='post_create'),
    path('posts/edit/<pk>', views.PostUpdateView.as_view(), name='post_edit'),
    path('posts/delete/<pk>', views.PostDeleteView.as_view(), name='post_delete'),
    path('posts/<pk>', views.PostDetailView.as_view(), name='post_details'),
    path('comments/new/<int:post>', views.CommentCreateView.as_view(), name='comment_create'),
    path('comments/edit/<pk>', views.CommentUpdateView.as_view(), name='comment_edit'),
    path('comments/delete/<pk>', views.CommentDeleteView.as_view(), name='comment_delete'),
    path('about/', views.about, name='about'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='login.html'), name = "login"),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name = "logout"),
    path('accounts/signup/', views.UserCreateView.as_view(), name = "signup"),
]

django_blog/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.urls import reverse
# Create your models here.

class BlogPost (models.Model):
    
    title = models.CharField(max_length = 128)
    body_text = models.TextField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)
    published_at = models.DateTimeField(null=True, blank = True)

    def publish(self):
        self.published_at = timezone.now()
        return self.published_at

    def get_absolute_url(self):
        return reverse('blog:post_details', args=[str(self.id)])

    def __str__(self):
        return self.title


class PostComment (models.Model):
    post = models.ForeignKey(BlogPost, on_delete=models.CASCADE, related_name = "comments")
    comment_text = models.TextField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    created_at = models.DateTimeField(default=timezone.now)

    def get_absolute_url(self):
        return reverse('blog:comment_details', args=[str(self.id)])

    def __str__(self):
        return self.comment_text

blog/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from blog.models import BlogPost, PostComment
from django.forms import Textarea, TextInput

class BlogPostForm (ModelForm):
    class Meta:
        model = BlogPost
        fields = ("title", "body_text")
        widgets = {
                'title': TextInput(attrs={'class': "title-input", "placeholder":"Title"}),
                'body_text': Textarea(attrs={'class': "editable medium-editor-textarea", "cols":1, "rows": 1}),
            }

class PostCommentForm (ModelForm):
    class Meta:
        model = PostComment
        fields = ("comment_text",)
        widgets = {
                'comment_text': Textarea(attrs={'class': "editable medium-editor-textarea", "cols":1, "rows": 1}),
            }

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import (ListView, DetailView)
from django.views.generic.edit import (CreateView, UpdateView, DeleteView)
from blog.models import BlogPost, PostComment
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.shortcuts import render
from django.forms import Textarea
from blog.forms import BlogPostForm, PostCommentForm


# Create your views here.
# @login_required
def about(request):
    return render(request, "about.html")

@login_required
def publish_post(request, **kwargs):
    id = kwargs["pk"]
    post = BlogPost.objects.get(id=id)
    post.publish()
    post.save()
    return render (request, "blogpost_publish.html", context={"id":id})


class UserCreateView(CreateView):
    form_class = UserCreationForm
    template_name = "accounts/signup.html"
    success_url = "/"

# Post views
class PostListView(ListView):
    paginate_by = 10
    model = BlogPost

class MyPostsListView(ListView):
    paginate_by = 10
    model = BlogPost
    template_name = 'myposts_list.html'

    def get_queryset(self):
        self.author = get_object_or_404(User, username = self.request.user.username)
        return BlogPost.objects.filter(author=self.author)

class PostCreateView(CreateView):
    model = BlogPost
    form_class = BlogPostForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class PostDetailView(DetailView):
    model = BlogPost

class PostUpdateView(UpdateView):
    model = BlogPost
    form_class = BlogPostForm

class PostDeleteView(DeleteView):
    model = BlogPost
    success_url = reverse_lazy('blog:post_list')


# Comment views
class CommentCreateView(CreateView):
    model = PostComment
    form_class = PostCommentForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.post = get_object_or_404(BlogPost, id=self.kwargs['post'])
        return super().form_valid(form)

    def get_success_url(self):
        success_url = reverse_lazy('blog:post_details', args = [self.object.post.pk])
        return success_url

class CommentUpdateView(UpdateView):
    model = PostComment
    form_class = PostCommentForm

    def get_success_url(self):
        success_url = reverse_lazy('blog:post_details', args = [self.object.post.pk])
        return success_url

class CommentDeleteView(DeleteView):
    model = PostComment
    def get_success_url(self):
        success_url = reverse_lazy('blog:post_details', args = [self.object.post.pk])
        return success_url

blog/templates/accounts/login.html
{% extends "blog_base.html" %}
{% block body_block %}
  <h1>This is login page</h1>
  <div class="card">
    <div class="card-body">
      <form method="post" action="{% url 'blog:login' %}">
          {% csrf_token %}
          <table>
          <tr>
              <td>{{ form.username.label_tag }}</td>
              <td>{{ form.username }}</td>
          </tr>
          <tr>
              <td>{{ form.password.label_tag }}</td>
              <td>{{ form.password }}</td>
          </tr>
          </table>


          <input class="btn btn-outline-primary btn-sm" type="submit" value="Login">
          <input type="hidden" name="next" value="{{ next }}">
      </form>

    </div>
  </div>


{% endblock body_block %}

blog/templates/accounts/signup.html
{% extends "blog_base.html" %}
{% block body_block %}

<h1>Register new user</h1>
<div class="card">
  <div class="card-body">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <a href="{% url "blog:post_list" %}" class="btn btn-outline-secondary btn-sm">Cancel</a>
        <input class="btn btn-outline-danger btn-sm" type="submit" value="Signup">
    </form>

  </div>
</div>


{% endblock body_block %}

blog/templates/blog/about.html
{% extends "blog_base.html" %}
{% load blog_extras %}
{% block body_block %}

<h1>This is about page!</h1>
<div class="card">
  <div class="card-body">
    <p>This blog support two type of users:</p>
    <h3>Regular Users can:</h3>
    <ul>
      <li>View list of all "Published" blogposts</li>
      <li>View list of their own "Published" posts and "Drafts"</li>
      <li>Create new blogpost "Drafts" (which then need to be approved and published by Admin)</li>
      <li>Edit/Delete their own blogposts</li>
      <li>Comment blogposts</li>
      <li>Edit/Delete their own comments</li>
    </ul>
    <p>You may register a new user via SignUp page here <span> <a class="btn btn-outline-secondary btn-sm" href="{% url "blog:signup" %}">Signup</a></span></p>

    <h3>Admin User can:</h3>
    <ul>
      <li>Do everything that a Regular user can</li>
      <li>Publish post "Drafts"</li>
      <li>Delete other user's blogposts</li>
      <li>Delete other user's comments</li>
    </ul>
    <p>Admin user credentials: admin/newpass1234</p>

  </div>
</div>

{% endblock body_block %}

blog/templates/blog/blog_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Fontawesome -->
    <script src="https://kit.fontawesome.com/68f06e867f.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Serif+JP&family=Play&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" href="{% static "css/blog.css" %}">
    <title></title>
  </head>


  <body>
    <!-- Navbar -->
    <div class="container-fullwidth navbar-container">
      <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url "blog:post_list" %}">Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Nav Left Section -->
        <div class="collapse navbar-collapse dual-collapse2">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{% url "blog:about" %}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "admin:index" %}">Admin</a>
            </li>
          </ul>
        </div>

        <!-- Nav Right Section-->
        <div class="navbar-collapse collapse dual-collapse2">
          <ul class="navbar-nav ml-auto">
              {% if user.is_authenticated %}
              <li class="nav-item">
                  <a class="nav-link" href="{% url "blog:post_create" %}">New Post</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url "blog:mypost_list" %}">My Posts</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url "blog:logout" %}">Logout</a>
              </li>
              {% else %}
              <li class="nav-item">
                  <a class="nav-link" href="{% url "blog:login" %}">Login</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url "blog:signup" %}">Signup</a>
              </li>
              {% endif %}

          </ul>
        </div>

      </nav>

    </div>

    <!-- Body block -->
    <div class="container blogbody">
      {% block body_block %}
      {% endblock body_block %}
    </div>

    <!-- Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


    <!-- Medium style editor -->
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
    <script>
      var editor = new MediumEditor('.editable', {
      // spellcheck: false,
      placeholder: {
        hideOnClick: false
      },
      buttonLabels:'fontawesome',
      toolbar: {
          /* These are the default options for the toolbar,
             if nothing is passed this is what is used */
          allowMultiParagraphSelection: true,
          buttons: ['bold', 'italic', 'underline', 'anchor', 'h2', 'h3', 'quote'],
          diffLeft: 0,
          diffTop: -10,
          firstButtonClass: 'medium-editor-button-first',
          lastButtonClass: 'medium-editor-button-last',
          relativeContainer: null,
          standardizeSelectionStart: false,
          static: true,
          /* options which only apply when static is true */
          align: 'center',
          sticky: true,
          updateOnEmptySelection: true
      }
    });
    </script>
  </body>
</html>

blog/templates/blog/blogpost_confirm_delete.html
{% extends "blog_base.html" %}
{% block body_block%}

<div class="card">
  <div class="card-body">
    <form method="post">
        {% csrf_token %}

          <h5 class="card-title">Are you sure you want to delete this Post?</h5>
          <p class="card-text"><em>{{object|safe}}</em></p>

        <a href="{% url "blog:post_list" %}" class="btn btn-outline-secondary btn-sm">Cancel</a>
        <input class="btn btn-outline-danger btn-sm" type="submit" value="Confirm">
    </form>

  </div>
</div>

{% endblock body_block %}

blog/templates/blog/blogpost_detail.html
{% extends "blog_base.html" %}
{% load blog_extras %}
{% block body_block%}
    <div class="card">
    <div class="card-body">
      <p class="card-subtitle small mb-2 text-muted">
        <span>Created by {{object.author}}
          {% if object.published_at %}
            at: {{object.published_at|date:"H:i d/m/Y"}}
          {% endif %}
        </span>
        <span class="publishedBtn">
          <!-- "My Post" badge -->
          {% if object.author == user %}
            <span class="badge badge-info">My Post</span>
          {% endif %}
          <!-- Only admin can publish drafts -->
          {% if not object.published_at and user|has_group:"blog_editors" %}
            <button type="button" class="btn btn-sm btn-outline-secondary" href="{% url "blog:post_publish" object.id %}">Publish</button>
          {% elif not object.published_at %}
            <span class="badge badge-pill badge-light">Pending</span>
          {% endif %}
        </span>
      </p>
      <h1 class="card-title">{{object.title}}</h1>
      {% autoescape off %}
        <p class="card-text">{{object.body_text}}</p>
      {% endautoescape %}

    </div>
    <ul class="list-group list-group-flush">
      {% for comment in object.comments.all %}

      <li class="list-group-item">
        <p class="card-subtitle small mb-2 text-muted">
          <span>Commented by {{comment.author}}
              at: {{comment.created_at|date:"H:i d/m/Y"}}
          </span>
            <!-- "My Comment" badge -->
          <span class="badges-area">
          {% if comment.author == user %}
            <span class="badge badge-info">My Comment</span>
          {% endif %}
          </span>
        </p>


        <div class="comment">
          {% autoescape off %}
          {{comment}}
          {% endautoescape %}
        </div>


        <!-- TOOLBAR -->
        <!-- Comment owner and post author can get access to comment tollbar -->
        {% if comment.author == user or object.author == user or user|has_group:"blog_editors" %}
        <div class="small mb-2 text-muted card-toolbar">
          {% if comment.author == user %}
          <a class="card-toolbar-options" href="{% url "blog:comment_edit" comment.id %}">
            <i class="far fa-edit"></i>
            <span>Edit</span>
          </a>
          {% endif %}
          <a class="card-toolbar-options" href="{% url "blog:comment_delete" comment.id %}">
            <i class="far fa-trash-alt"></i>
            <span>Delete</span>
          </a>
        </div>
        {% endif %}
      </li>
      {% endfor %}

      <!-- New Comments form -->
      <li class="list-group-item">
        <p class="card-subtitle mb-2 ">
          <span> Add your comment </span>
        </p>
        <div class="comment">
          <form class="" action="{% url "blog:comment_create" object.id %}" method="post">
            {%csrf_token%}
            <div class="card comment-editor-area">
              <div class="card-body">
                  <textarea class = "editable medium-editor-textarea" name="comment_text" rows="8" cols="80" placeholder="Type yor text here"></textarea>
              </div>
            </div>
            <input type="submit" value="Save">
          </form>
        </div>

      </li>
    </ul>

  </div>


{% endblock body_block %}

blog/templates/blog/blogpost_form.html
{% extends "blog_base.html" %}
{% block body_block%}
  <h1>Create/edit a blogpost!</h1>

  <form method="post">
    {% csrf_token %}

    <div class="card editor-area">
      <h3 class="card-title editor-title">{{ form.title }}</h3>
      <div class="card-body">

        {{ form.body_text}}
      </div>
      <input class="card-toolbar-options" type="submit" value="Save">
    </div>

  </form>


{% endblock body_block %}

blog/templates/blog/blogpost_list.html
{% extends "blog_base.html" %}
{% load blog_extras %}
{% block body_block%}

  <h1>Welcome to the Blog!</h1>
  {% for blog in page_obj%}
  <!-- for admin user we show all posts published and not_published, for author we show all published + his/her not published -->
    {% if blog.published_at or user|has_group:"blog_editors" or blog.author == user %}
      <div class="card list-card">
        <div class="card-body">
          <!-- CLICKABLE CARD BODY -->
          <a class="postcard" href="{% url "blog:post_details" blog.id %}">
            <p class="card-subtitle small mb-2 text-muted">
              <span>Created by {{blog.author}}
                {% if blog.published_at %}
                  at: {{blog.published_at|date:"H:i d/m/Y"}}
                {% endif %}
              </span>
              <span class="badges-area">
                <!-- "My Post" badge -->
                {% if blog.author == user and blog.published_at %}
                  <span class="badge badge-info">My Post</span>
                {% elif not blog.published_at %}
                  <span class="badge badge-pill badge-warning">Pending</span>
                {% endif %}
              </span>
            </p>
            <h5 class="card-title">{{blog.title}}</h5>
            {% autoescape off %}
              <p class="card-text">{{blog.body_text|truncatechars_html:320}}</p>
            {% endautoescape %}
          </a>

          <!-- CARD TOOLBAR-->
          <div class="small mb-2 text-muted card-toolbar">
            <span class="card-subtitle">{{blog.comments.count}} Comments</span>
            <!-- Toolbar editing options are visible only for author and superuser -->
            {% if blog.author == user or user.is_superuser %}
            <a class="card-toolbar-options" href="{% url "blog:post_edit" blog.id %}">
              <i class="far fa-edit"></i>
              <span>Edit</span>
            </a>
            <a class="card-toolbar-options" href="{% url "blog:post_delete" blog.id %}">
              <i class="far fa-trash-alt"></i>
              <span>Delete</span>
            </a>
            {% endif %}

            <!-- Only admin can publish drafts -->
            {% if not blog.published_at and user|has_group:"blog_editors" %}
              <a class="card-toolbar-options publish-btn" href="{% url "blog:post_publish" blog.id %}">
                <i class="fas fa-check"></i>
                <span>Publish</span>
              </a>
            {% endif %}
          </div>

        </div>
      </div>
    {% endif %}
  {% endfor %}

  {% if not blogpost_list %}
    <p>No Posts here yet. You can create the first one.</p>
  {% endif %}

  <!-- Pagination -->
  <div class="pagination">
      <span class="step-links">
          {% if page_obj.has_previous %}
              <a href="?page=1">&laquo; first</a>
              <a href="?page={{ page_obj.previous_page_number }}">previous</a>
          {% endif %}

          <span class="current">
              Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
          </span>

          {% if page_obj.has_next %}
              <a href="?page={{ page_obj.next_page_number }}">next</a>
              <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
          {% endif %}
      </span>
  </div>
  <br>


{% endblock body_block %}

blog/templates/blog/blogpost_publish.html
{% extends "blog_base.html" %}
{% block body_block%}

  <div class="card">
    <div class="card-body">
        <h5 class="card-title">The Post with id: {{id}} was published!</h5>
        <p class="card-text"><em>Back to all posts</em></p>
        <a href="{% url "blog:post_list" %}" class="btn btn-outline-secondary btn-sm">Back</a>
    </div>
  </div>
{% endblock body_block %}

blog/templates/blog/myposts_list.html
{% extends "blog_base.html" %}
{% load blog_extras %}
{% block body_block%}
  <h1>My Posts!</h1>

  {% for blog in page_obj%}
    <div class="card list-card">
      <div class="card-body">
        <!-- CLICKABLE CARD BODY -->
        <a class="postcard" href="{% url "blog:post_details" blog.id %}">
          <p class="card-subtitle small mb-2 text-muted">
            <span>Created by {{blog.author}}
              {% if blog.published_at %}
                at: {{blog.published_at|date:"H:i d/m/Y"}}
              {% endif %}
            </span>
            <span class="badges-area">
              <!-- "My Post" badge -->
              {% if blog.published_at %}
                <span class="badge badge-info">Published</span>
              {% else %}
                <span class="badge badge-warning">Pending</span>
              {% endif %}
            </span>
          </p>
          <h5 class="card-title">{{blog.title}}</h5>
          {% autoescape off %}
          <p class="card-text">{{blog.body_text|truncatechars_html:320}}</p>
          {% endautoescape %}
        </a>

        <!-- CARD TOOLBAR -->
        <div class="small mb-2 text-muted card-toolbar">
          <span class="card-subtitle">{{blog.comments.count}} Comments</span>
          <!-- <p class="card-subtitle small text-muted"> {{blog.comments.count}} Comments</p> -->
          {% if blog.author == user %}

          <a class="card-toolbar-options" href="{% url "blog:post_edit" blog.id %}">
            <i class="far fa-edit"></i>
            <span>Edit</span>
          </a>
          <a class="card-toolbar-options" href="{% url "blog:post_delete" blog.id %}">
            <i class="far fa-trash-alt"></i>
            <span>Delete</span>
          </a>

          {% endif %}
          <!-- Only admin can publish drafts -->
          {% if not blog.published_at and user|has_group:"blog_editors" %}
            <a class="card-toolbar-options publish-btn" href="{% url "blog:post_publish" blog.id %}">
              <i class="fas fa-check"></i>
              <span>Publish</span>
            </a>
          {% endif %}
        </div>

      </div>
    </div>

  {% endfor %}
  {% if not blogpost_list %}
    <p>No Posts here yet. You can create the first one.</p>
  {% endif %}

  <div class="pagination">
      <span class="step-links">
          {% if page_obj.has_previous %}
              <a href="?page=1">&laquo; first</a>
              <a href="?page={{ page_obj.previous_page_number }}">previous</a>
          {% endif %}

          <span class="current">
              Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
          </span>

          {% if page_obj.has_next %}
              <a href="?page={{ page_obj.next_page_number }}">next</a>
              <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
          {% endif %}
      </span>
  </div>
  
{% endblock body_block %}

blog/templates/blog/postcomment_confirm_delete.html
{% extends "blog_base.html" %}
{% block body_block%}

<div class="card">
  <div class="card-body">
    <form method="post">
        {% csrf_token %}

          <h5 class="card-title">Are you sure you want to delete this comment?</h5>
          <p class="card-text"><em>{{object|safe}}</em></p>

        <a href="{% url "blog:post_details" object.post.id %}" class="btn btn-outline-secondary btn-sm">Cancel</a>
        <input class="btn btn-outline-danger btn-sm" type="submit" value="Confirm">
    </form>

  </div>
</div>

{% endblock body_block %}

blog/templates/blog/postcomment_form.html
{% extends "blog_base.html" %}
{% block body_block%}
  <h1>Create/edit a comment!</h1>

  <div class="comment">
    <form method="post">
      {% csrf_token %}

      <div class="card comment-editor-area">
        <div class="card-body">
            {{form.comment_text}}
        </div>
        <input class="card-toolbar-options" type="submit" value="Save">
      </div>
    </form>
  </div>



{% endblock body_block %}